### ISSUE TITLE
youtube id error

### ISSUE THREAD

**Issue by wprodell** [farmerbb/Taskbar#160] opened 2020-11-09 15:28 UTC
play YouTube there is a problem with written error id, using browser chrom and opera
![IMG_20201028_224936](https://user-images.githubusercontent.com/55977567/98560969-4ece5e00-22e3-11eb-89fc-36819af6e17a.jpg)

**Comment by farmerbb** [comment] 2020-11-29 06:03
This is not an issue caused by Taskbar - closing.

**Closed by farmerbb** 2020-11-29 06:03 UTC
